kumuluzee:
  name: accountoptions-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/usersDS
      connection-url: jdbc:postgresql://localhost:5435/users
      username: postgres
      password: postgres
      max-pool-size: 20